markdown: redcarpet
redcarpet:
  extensions:
    - smart
    - strikethrough
    - superscript
    - tables
    - with_toc_data
    - footnotes
gems:
  - jekyll-feed
  - jemoji

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: post

name: Nauman Ahmad
email: nauman.ahmad@nyu.edu
domain: naumanahmad.me
gravatar: dab7dc58b6d9b6702ddfa595d525b62c

nav:
  pages:
    - name: Home
      href: /

    - name: Projects
      href: /projects.html

    - name: Résumé
      href: /resume.html

  links:
    - name: GitHub
      href: https://github.com/itsnauman
      icon: fa-github-alt

    - name: LinkedIn
      href: https://ca.linkedin.com/in/itsnauman
      icon: fa-linkedin

    - name: Email
      href: mailto:nauman.ahmad@nyu.edu
      icon: fa-envelope
